### ISSUE TITLE
Marketplace Settings: Stewards -  System is showing up as a user that can be assigned orgs and should not appear

### ISSUE THREAD

**Issue by mparizernc** [aml-development/ozp-center#127] opened 2015-03-16 11:38 UTC
I have seen this with both H2 (file) and mariaDB, when I go to Marketplace Settings and the Stewards tab the System user appears as a user that can be assigned orgs. The system user should not appear on the list of users that can be assigned orgs.

**Comment by akonsowski** [comment] 2016-05-23 16:07
is this still an issue? i was not able to reproduce on LS

**Comment by lsemesky** [comment] 2016-10-06 21:58
I am also not able to reproduce. Are you able to reproduce @tdressel ?

**Comment by tdressel** [comment] 2016-10-13 17:33
Checked in Center Settings | Stewards Tab 
RESULTS - System is no longer listed as a user.

**Comment by tdressel** [comment] 2016-11-15 20:42
Passed on Staging.

**Closed** 2016-11-15 20:42 UTC
Labels: 0 - Backlog, bug
